export const data = [
    {
      id: 1,
      name: "Eric Pridz",
      style: "Techno",
      location: "Buenos Aires",
      date: "11 de Febrero de 2023",
      price: 14000,
      banner: "https://res.cloudinary.com/dmxt0frnf/image/upload/v1670811941/Eric_Pridz_gsgwcn.jpg",
    },
    {
      id: 2,
      name: "Artbat",
      style: "Melodic-Techno",
      location: "Mar Del Plata",
      date: "07 de Enero de 2023",
      price: 12000,
      banner: "https://res.cloudinary.com/dmxt0frnf/image/upload/v1670811941/Artbat_ktr7zt.jpg",
    },
    {
      id: 3,
      name: "Hernán Cattáneo",
      style: "Progressive",
      location: "Buenos Aires",
      date: "04 de Marzo de 2023",
      price: 15000,
      banner: "https://res.cloudinary.com/dmxt0frnf/image/upload/v1670811942/Hern%C3%A1n_Catt%C3%A1neo_ngyl6d.jpg",
    },
    {
      id: 4,
      name: "Monolink - Elke Kleijn",
      style: "Melodic-Techno",
      location: "Punta Del Este",
      date: "03 de Enero de 2023",
      price: 12000,
      banner: "https://res.cloudinary.com/dmxt0frnf/image/upload/v1670811941/Monolink_xoc6v8.jpg",
    },
    {
      id: 5,
      name: "Dennis Cruz",
      style: "Tech-House",
      location: "Buenos Aires",
      date: "17 de Diciembre de 2022",
      price: 8000,
      banner: "https://res.cloudinary.com/dmxt0frnf/image/upload/v1670811941/Dennis_Cruz_xri5mh.jpg",
    },
    {
      id: 6,
      name: "Paco Osuna",
      style: "Tech-House",
      location: "Cordoba",
      date: "16 de Diciembre de 2022",
      price: 9000,
      banner: "https://res.cloudinary.com/dmxt0frnf/image/upload/v1670811942/Paco_Osuna_fsqxur.jpg",
    },
    {
      id: 7,
      name: "Marco Carola - Hot Since 82",
      style: "Tech-House",
      location: "Punta Del Este",
      date: "03 de Enero de 2023",
      price: 11000,
      banner: "https://res.cloudinary.com/dmxt0frnf/image/upload/v1670811941/Marco_Carola_-_HS_82_dxtywr.jpg",
    },
    {
      id: 8,
      name: "Nick Warren",
      style: "Progressive",
      location: "Villa Gesell",
      date: "26 de Enero de 2023",
      price: 10000,
      banner: "https://imgproxy.ra.co/_/quality:66/w:1500/rt:fill/aHR0cHM6Ly9pbWFnZXMucmEuY28vZTg2MTMyNDk3ZDE0MGE0YTM3ZmNlZTJmYWI1ZjA0M2QyMDk0MDAxYy5qcGc=",
    },
    {
      id: 9,
      name: "Fideles",
      style: "Techno",
      location: "Cordoba",
      date: "13 de Enero de 2023",
      price: 9000,
      banner: "https://dvuq2nras8x3d.cloudfront.net/events/e3bae09f-01a1-4f24-b79c-a7d3fdebb744.jpeg",
    },
    {
      id: 10,
      name: "John Digweed",
      style: "Progressive",
      location: "Villa Gesell",
      date: "19 de Enero de 2023",
      price: 9000,
      banner: "https://res.cloudinary.com/dmxt0frnf/image/upload/v1670816406/John_Digweeg_ahwrzl.jpg",
    },
  ];